### ISSUE TITLE
Duplicate plugin/preset detected after configuring Babel for Parcel

### ISSUE THREAD

**Issue by bratnick** [btholt/complete-intro-to-react-v5#97] opened 2020-06-10 15:00 UTC
![image](https://user-images.githubusercontent.com/30936967/84283870-25a17a00-ab59-11ea-852b-651cd0ad1cbe.png)

**Comment by danfrenette** [comment] 2020-06-10 23:05
I'm getting this error as well. Would love some assistance as this course has been great so far!
<img width="832" alt="Terminal_—_tmux_—_85×39_and_🚨_Build_Error" src="https://user-images.githubusercontent.com/8248100/84327407-3b10a700-ab4d-11ea-88a3-6c8fe3b20861.png">

Here's a link to my repo, everything's been done on the master branch so far: https://github.com/danfrenette/frontend-masters-beginner-react

**Comment by danfrenette** [comment] 2020-06-11 11:23
Actually, it looks like this is a duplicate of #93 

@btholt it'd be super appreciated to get your input on these.

**Comment by bratnick** [comment] 2020-06-12 17:11
@danfrenette , did the solution for #93 work for you?
Its not working for me.
@btholt , it'd be appreciated if you could help us out here !

**Comment by danfrenette** [comment] 2020-06-13 23:44
@bratnick Okay I just figured it out (and by "figured it out" I mean I noticed the "Debugging" section of the README 🤦 )

You have to remove the cache that parcel uses after you follow the instructions in the other issue. So in full order, that's:
1. Remove the line `` from your `.babelrc` file
1. Run `rm -rf .cache/ dist/` in the root directory of the project. I also removed the node modules at this point, but that might not be necessary (`rm -rf node_modules`).
1. Run `yarn` to get all your packages back.
1. Run `npm run dev` and hopefully your project should be back online. You can confirm the issue was fixed if your linter isn't complaining about the `state` var being set in the `src/Details.js` file.

I hope this helps!

**Comment by laniehei** [comment] 2020-06-15 15:07
It looks like this issue has been solved! Closing this. Please reopen if there are further issues.

**Closed by laniehei** 2020-06-15 15:07 UTC

**Comment by AashiqinCode** [comment] 2020-09-04 09:43
> @bratnick Okay I just figured it out (and by "figured it out" I mean I noticed the "Debugging" section of the README 🤦 )
> 
> You have to remove the cache that parcel uses after you follow the instructions in the other issue. So in full order, that's:
> 
> 1. Remove the line `"plugins": ["@babel/plugin-proposal-class-properties"]` from your `.babelrc` file
> 2. Run `rm -rf .cache/ dist/` in the root directory of the project. I also removed the node modules at this point, but that might not be necessary (`rm -rf node_modules`).
> 3. Run `yarn` to get all your packages back.
> 4. Run `npm run dev` and hopefully your project should be back online. You can confirm the issue was fixed if your linter isn't complaining about the `state` var being set in the `src/Details.js` file.
> 
> I hope this helps!

But for rm -rf .cache/ dist/,it says,
'rm' is not recognized as an internal or external command,
operable program or batch file.
